# Generated by Django 3.1 on 2020-08-19 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('about', models.TextField(max_length=1000)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50)),
                ('othernames', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('headshot', models.ImageField(upload_to='developers')),
                ('role', models.CharField(max_length=50)),
                ('project', models.ManyToManyField(to='projects.Project')),
            ],
        ),
    ]
