# Generated by Django 3.1 on 2020-08-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_date_released'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_released',
            field=models.DateField(blank=True, null=True),
        ),
    ]
